### ISSUE TITLE
error running yo samsara - missing module chalk

### ISSUE THREAD

**Issue by rakar** [richardkopelow/generator-samsara#1]
========let isText = null==============
            ^^^^^^
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

**Comment by richardkopelow** [comment]
I have tried it on Windows and Ubuntu and I am not seeing the problem, though I don't have a Mac to sets it on.

**Comment by richardkopelow** [comment]
I have tested this and it works.
